routes/web.php
    <?php

    use App\Http\Controllers\AlamatPengirimanController;
    use App\Http\Controllers\CartController;
    use App\Http\Controllers\CartDetailController;
    use App\Http\Controllers\CustomerController;
    use App\Http\Controllers\DashboardController;
    use App\Http\Controllers\HomepageController;
    use App\Http\Controllers\ImageController;
    use App\Http\Controllers\KategoriController;
    use App\Http\Controllers\LaporanController;
    use App\Http\Controllers\LatihanController;
    use App\Http\Controllers\ProdukController;
    use App\Http\Controllers\ProdukPromoController;
    use App\Http\Controllers\SlideshowController;
    use App\Http\Controllers\TransaksiController;
    use App\Http\Controllers\UserController;
    use App\Http\Controllers\WishlistController;
    use Illuminate\Support\Facades\Auth;
    use Illuminate\Support\Facades\Route;

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    Route::get('/', [HomepageController::class, 'index']);
    Route::get('/about', [HomepageController::class, 'about']);
    Route::get('/kontak', [HomepageController::class, 'kontak']);
    Route::get('/kategori', [HomepageController::class, 'kategori']);
    Route::get('/kategori/{slug}', [HomepageController::class, 'kategoribyslug']);
    Route::get('/produk', [HomepageController::class, 'produk']);
    Route::get('produk/{id}', [HomepageController::class, 'produkdetail']);

    Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
        Route::get('/', [DashboardController::class, 'index']);
        // route kategori
        Route::resource('kategori', KategoriController::class);
        // route produk
        Route::resource('produk', ProdukController::class);
        // route customer
        Route::resource('customer', CustomerController::class);
        // route transaksi
        Route::resource('transaksi', TransaksiController::class);
        // profil
        Route::get('profil', [UserController::class, 'index']);
        // setting profil
        Route::get('setting', [UserController::class, 'setting']);
        // form laporan
        Route::get('laporan', [LaporanController::class, 'index']);
        // proses laporan
        Route::get('proseslaporan', [LaporanController::class, 'proses']);

        // image
        Route::get('image', [ImageController::class, 'index']);
        // simpan image
        Route::post('image', [ImageController::class, 'store']);
        // hapus image by id
        Route::delete('image/{id}', [ImageController::class, 'destroy']);


        // upload image kategori
        Route::post('imagekategori', [KategoriController::class, 'uploadimage']);
        // hapus image kategori
        Route::delete('imagekategori/{id}', [KategoriController::class, 'deleteimage']);

        // upload image produk
        Route::post('produkimage', [ProdukController::class, 'uploadimage']);
        // hapus image produk
        Route::delete('produkimage/{id}', [ProdukController::class, 'deleteimage']);

        // hapus image produk
        Route::delete('produkimage/{id}', [ProdukController::class, 'deleteimage']);
        // slideshow
        Route::resource('slideshow', SlideshowController::class);

        // produk promo
        Route::resource('promo', ProdukPromoController::class);
        // load async produk
        Route::get('loadprodukasync/{id}', [ProdukController::class, 'loadasync']);
        // wishlist
        Route::resource('wishlist', WishlistController::class);
    });
    // shopping cart
    Route::group(['middleware' => 'auth'], function () {
        // cart
        Route::resource('cart', CartController::class);
        Route::patch('kosongkan/{id}', [CartController::class, 'kosongkan']);
        // cart detail
        Route::resource('cartdetail', CartDetailController::class);

        // alamat pengiriman
        Route::resource('alamatpengiriman', AlamatPengirimanController::class);
        // checkout
        Route::get('checkout', [CartController::class, 'checkout']);
    });

    // Route::get('/', function () {
    //     return view('welcome');
    // });
    // Route::get('/halo', function () {
    //     return "Halo nama saya fadlur";
    // });
    // Route::get('/latihan', [LatihanController::class,'index']);
    // Route::get('/blog/{id}', [LatihanController::class,'blog']);
    // Route::get('/blog/{idblog}/komentar/{idkomentar}',[LatihanController::class,'komentar']);
    // Route::get('/beranda', [LatihanController::class,'beranda']);

    Auth::routes();
    Route::get('/home', function () {
        return redirect('/admin');
    });

app/Models/Cart.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    protected $table = 'cart';
    protected $fillable = [
        'user_id',
        'no_invoice',
        'status_cart',
        'status_pembayaran',
        'status_pengiriman',
        'no_resi',
        'ekspedisi',
        'subtotal',
        'ongkir',
        'diskon',
        'total',
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function detail()
    {
        return $this->hasMany(CartDetail::class, 'cart_id');
    }

    public function updatetotal($itemcart, $subtotal)
    {
        $this->attributes['subtotal'] = $itemcart->subtotal + $subtotal;
        $this->attributes['total'] = $itemcart->total + $subtotal;
        self::save();
    }
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Models\AlamatPengiriman;
use App\Models\Cart;
use Illuminate\Http\Request;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $itemuser = $request->user(); //ambil data user
        $itemcart = Cart::where('user_id', $itemuser->id)
            ->where('status_cart', 'cart')
            ->first();
        if ($itemcart) {
            $data = array(
                'title' => 'Shopping Cart',
                'itemcart' => $itemcart
            );
            return view('cart.index', $data)->with('no', 1);
        } else {
            return abort('404');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function kosongkan($id)
    {
        $itemcart = Cart::findOrFail($id);
        $itemcart->detail()->delete(); //hapus semua item di cart detail
        $itemcart->updatetotal($itemcart, '-' . $itemcart->subtotal);
        return back()->with('success', 'Cart berhasil dikosongkan');
    }

    public function checkout(Request $request)
    {
        $itemuser = $request->user();
        $itemcart = Cart::where('user_id', $itemuser->id)
            ->where('status_cart', 'cart')
            ->first();
        $itemalamatpengiriman = AlamatPengiriman::where('user_id', $itemuser->id)
            ->where('status', 'utama')
            ->first();
        if ($itemcart) {
            $data = array(
                'title' => 'Checkout',
                'itemcart' => $itemcart,
                'itemalamatpengiriman' => $itemalamatpengiriman
            );
            return view('cart.checkout', $data)->with('no', 1);
        } else {
            return abort('404');
        }
    }
}

resources/views/cart/checkout.blade.php
@extends('layouts.template')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col col-8">
                @if (count($errors) > 0)
                    @foreach ($errors->all() as $error)
                        <div class="alert alert-warning">{{ $error }}</div>
                    @endforeach
                @endif
                @if ($message = Session::get('error'))
                    <div class="alert alert-warning">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                <div class="row mb-2">
                    <div class="col col-12 mb-2">
                        <div class="card">
                            <div class="card-header">
                                Item
                            </div>
                            <div class="card-body">
                                <table class="table table-stripped">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Produk</th>
                                            <th>Harga</th>
                                            <th>Diskon</th>
                                            <th>Qty</th>
                                            <th>Subtotal</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($itemcart->detail as $detail)
                                            <tr>
                                                <td>
                                                    {{ $no++ }}
                                                </td>
                                                <td>
                                                    {{ $detail->produk->nama_produk }}
                                                    <br />
                                                    {{ $detail->produk->kode_produk }}
                                                </td>
                                                <td>
                                                    {{ number_format($detail->harga, 2) }}
                                                </td>
                                                <td>
                                                    {{ number_format($detail->diskon, 2) }}
                                                </td>
                                                <td>
                                                    {{ number_format($detail->qty, 2) }}
                                                </td>
                                                <td>
                                                    {{ number_format($detail->subtotal, 2) }}
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col col-12">
                        <div class="card">
                            <div class="card-header">Alamat Pengiriman</div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-stripped">
                                        <thead>
                                            <tr>
                                                <th>Nama Penerima</th>
                                                <th>Alamat</th>
                                                <th>No tlp</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @if ($itemalamatpengiriman)
                                                <tr>
                                                    <td>
                                                        {{ $itemalamatpengiriman->nama_penerima }}
                                                    </td>
                                                    <td>
                                                        {{ $itemalamatpengiriman->alamat }}<br />
                                                        {{ $itemalamatpengiriman->kelurahan }},
                                                        {{ $itemalamatpengiriman->kecamatan }}<br />
                                                        {{ $itemalamatpengiriman->kota }},
                                                        {{ $itemalamatpengiriman->provinsi }} -
                                                        {{ $itemalamatpengiriman->kodepos }}
                                                    </td>
                                                    <td>
                                                        {{ $itemalamatpengiriman->no_tlp }}
                                                    </td>
                                                    <td>
                                                        <a href="{{ route('alamatpengiriman.index') }}"
                                                            class="btn btn-success btn-sm">
                                                            Ubah Alamat
                                                        </a>
                                                    </td>
                                                </tr>
                                            @endif
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="card-footer">
                                <a href="{{ route('alamatpengiriman.index') }}" class="btn btn-sm btn-primary">
                                    Tambah Alamat
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col col-4">
                <div class="card">
                    <div class="card-header">
                        Ringkasan
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>No Invoice</td>
                                <td class="text-right">
                                    {{ $itemcart->no_invoice }}
                                </td>
                            </tr>
                            <tr>
                                <td>Subtotal</td>
                                <td class="text-right">
                                    {{ number_format($itemcart->subtotal, 2) }}
                                </td>
                            </tr>
                            <tr>
                                <td>Diskon</td>
                                <td class="text-right">
                                    {{ number_format($itemcart->diskon, 2) }}
                                </td>
                            </tr>
                            <tr>
                                <td>Total</td>
                                <td class="text-right">
                                    {{ number_format($itemcart->total, 2) }}
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="card-footer">
                        <form action="{{ route('transaksi.store') }}" method="post">
                            @csrf()
                            <button type="submit" class="btn btn-danger btn-block">Buat Pesanan</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cart/index.blade.php
@extends('layouts.template')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col col-md-8">
                @if (count($errors) > 0)
                    @foreach ($errors->all() as $error)
                        <div class="alert alert-warning">{{ $error }}</div>
                    @endforeach
                @endif
                @if ($message = Session::get('error'))
                    <div class="alert alert-warning">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                <div class="card">
                    <div class="card-header">
                        Item
                    </div>
                    <div class="card-body">
                        <table class="table table-stripped">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Produk</th>
                                    <th>Harga</th>
                                    <th>Diskon</th>
                                    <th>Qty</th>
                                    <th>Subtotal</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($itemcart->detail as $detail)
                                    <tr>
                                        <td>
                                            {{ $no++ }}
                                        </td>
                                        <td>
                                            {{ $detail->produk->nama_produk }}
                                            <br />
                                            {{ $detail->produk->kode_produk }}
                                        </td>
                                        <td>
                                            {{ number_format($detail->harga, 2) }}
                                        </td>
                                        <td>
                                            {{ number_format($detail->diskon, 2) }}
                                        </td>
                                        <td>
                                            <div class="btn-group" role="group">
                                                <form action="{{ route('cartdetail.update', $detail->id) }}"
                                                    method="post">
                                                    @method('patch')
                                                    @csrf()
                                                    <input type="hidden" name="param" value="kurang">
                                                    <button class="btn btn-primary btn-sm">
                                                        -
                                                    </button>
                                                </form>
                                                <button class="btn btn-outline-primary btn-sm" disabled="true">
                                                    {{ number_format($detail->qty, 2) }}
                                                </button>
                                                <form action="{{ route('cartdetail.update', $detail->id) }}"
                                                    method="post">
                                                    @method('patch')
                                                    @csrf()
                                                    <input type="hidden" name="param" value="tambah">
                                                    <button class="btn btn-primary btn-sm">
                                                        +
                                                    </button>
                                                </form>
                                            </div>
                                        </td>
                                        <td>
                                            {{ number_format($detail->subtotal, 2) }}
                                        </td>
                                        <td>
                                            <form action="{{ route('cartdetail.destroy', $detail->id) }}" method="post"
                                                style="display:inline;">
                                                @csrf
                                                {{ method_field('delete') }}
                                                <button type="submit" class="btn btn-sm btn-danger mb-2">
                                                    Hapus
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col col-md-4">
                <div class="card">
                    <div class="card-header">
                        Ringkasan
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>No Invoice</td>
                                <td class="text-right">
                                    {{ $itemcart->no_invoice }}
                                </td>
                            </tr>
                            <tr>
                                <td>Subtotal</td>
                                <td class="text-right">
                                    {{ number_format($itemcart->subtotal, 2) }}
                                </td>
                            </tr>
                            <tr>
                                <td>Diskon</td>
                                <td class="text-right">
                                    {{ number_format($itemcart->diskon, 2) }}
                                </td>
                            </tr>
                            <tr>
                                <td>Total</td>
                                <td class="text-right">
                                    {{ number_format($itemcart->total, 2) }}
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col">
                                <a href="{{ URL::to('checkout') }}" class="btn btn-primary btn-block">
                                    Checkout
                                </a>
                            </div>
                            <div class="col">
                                <form action="{{ url('kosongkan') . '/' . $itemcart->id }}" method="post">
                                    @method('patch')
                                    @csrf()
                                    <button type="submit" class="btn btn-danger btn-block">Kosongkan</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection