routes/web.php
    <?php

    use App\Http\Controllers\AlamatPengirimanController;
    use App\Http\Controllers\CartController;
    use App\Http\Controllers\CartDetailController;
    use App\Http\Controllers\CustomerController;
    use App\Http\Controllers\DashboardController;
    use App\Http\Controllers\HomepageController;
    use App\Http\Controllers\ImageController;
    use App\Http\Controllers\KategoriController;
    use App\Http\Controllers\LaporanController;
    use App\Http\Controllers\LatihanController;
    use App\Http\Controllers\ProdukController;
    use App\Http\Controllers\ProdukPromoController;
    use App\Http\Controllers\SlideshowController;
    use App\Http\Controllers\TransaksiController;
    use App\Http\Controllers\UserController;
    use App\Http\Controllers\WishlistController;
    use Illuminate\Support\Facades\Auth;
    use Illuminate\Support\Facades\Route;

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    Route::get('/', [HomepageController::class, 'index']);
    Route::get('/about', [HomepageController::class, 'about']);
    Route::get('/kontak', [HomepageController::class, 'kontak']);
    Route::get('/kategori', [HomepageController::class, 'kategori']);
    Route::get('/kategori/{slug}', [HomepageController::class, 'kategoribyslug']);
    Route::get('/produk', [HomepageController::class, 'produk']);
    Route::get('produk/{id}', [HomepageController::class, 'produkdetail']);

    Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
        Route::get('/', [DashboardController::class, 'index']);
        // route kategori
        Route::resource('kategori', KategoriController::class);
        // route produk
        Route::resource('produk', ProdukController::class);
        // route customer
        Route::resource('customer', CustomerController::class);
        // route transaksi
        Route::resource('transaksi', TransaksiController::class);
        // profil
        Route::get('profil', [UserController::class, 'index']);
        // setting profil
        Route::get('setting', [UserController::class, 'setting']);
        // form laporan
        Route::get('laporan', [LaporanController::class, 'index']);
        // proses laporan
        Route::get('proseslaporan', [LaporanController::class, 'proses']);

        // image
        Route::get('image', [ImageController::class, 'index']);
        // simpan image
        Route::post('image', [ImageController::class, 'store']);
        // hapus image by id
        Route::delete('image/{id}', [ImageController::class, 'destroy']);


        // upload image kategori
        Route::post('imagekategori', [KategoriController::class, 'uploadimage']);
        // hapus image kategori
        Route::delete('imagekategori/{id}', [KategoriController::class, 'deleteimage']);

        // upload image produk
        Route::post('produkimage', [ProdukController::class, 'uploadimage']);
        // hapus image produk
        Route::delete('produkimage/{id}', [ProdukController::class, 'deleteimage']);

        // hapus image produk
        Route::delete('produkimage/{id}', [ProdukController::class, 'deleteimage']);
        // slideshow
        Route::resource('slideshow', SlideshowController::class);

        // produk promo
        Route::resource('promo', ProdukPromoController::class);
        // load async produk
        Route::get('loadprodukasync/{id}', [ProdukController::class, 'loadasync']);
        // wishlist
        Route::resource('wishlist', WishlistController::class);
    });
    // shopping cart
    Route::group(['middleware' => 'auth'], function () {
        // cart
        Route::resource('cart', CartController::class);
        Route::patch('kosongkan/{id}', [CartController::class, 'kosongkan']);
        // cart detail
        Route::resource('cartdetail', CartDetailController::class);

        // alamat pengiriman
        Route::resource('alamatpengiriman', AlamatPengirimanController::class);
        // checkout
        Route::get('checkout', [CartController::class, 'checkout']);
    });

    // Route::get('/', function () {
    //     return view('welcome');
    // });
    // Route::get('/halo', function () {
    //     return "Halo nama saya fadlur";
    // });
    // Route::get('/latihan', [LatihanController::class,'index']);
    // Route::get('/blog/{id}', [LatihanController::class,'blog']);
    // Route::get('/blog/{idblog}/komentar/{idkomentar}',[LatihanController::class,'komentar']);
    // Route::get('/beranda', [LatihanController::class,'beranda']);

    Auth::routes();
    Route::get('/home', function () {
        return redirect('/admin');
    });

resources/views/promo/create.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col col-lg-6 col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Form Produk</h3>
                        <div class="card-tools">
                            <a href="{{ route('promo.index') }}" class="btn btn-sm btn-danger">
                                Tutup
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        @if (count($errors) > 0)
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-warning">{{ $error }}</div>
                            @endforeach
                        @endif
                        @if ($message = Session::get('error'))
                            <div class="alert alert-warning">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        <form action="{{ route('promo.store') }}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="produk_id">Produk</label>
                                <select name="produk_id" id="produk_id" class="form-control">
                                    <option value="">Pilih Produk</option>
                                    @foreach ($itemproduk as $produk)
                                        <option value="{{ $produk->id }}">{{ $produk->nama_produk }} -
                                            ({{ $produk->kode_produk }})</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="harga_awal">Harga Awal</label>
                                <input type="text" name="harga_awal" id="harga_awal" class="form-control"
                                    value={{ old('harga_awal') }}>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="form-group">
                                        <label for="diskon_persen">Diskon Persen</label>
                                        <input type="text" name="diskon_persen" id="diskon_persen" class="form-control"
                                            value={{ old('diskon_persen') }}>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <label for="diskon_nominal">Diskon Nominal</label>
                                        <input type="text" name="diskon_nominal" id="diskon_nominal" class="form-control"
                                            value={{ old('diskon_nominal') }}>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="harga_akhir">Harga Akhir</label>
                                <input type="text" name="harga_akhir" id="harga_akhir" class="form-control"
                                    value={{ old('harga_akhir') }}>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                                <button type="reset" class="btn btn-warning">Reset</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        // cari nominal diskon
        $('#diskon_persen').on('keyup', function() {
            var harga_awal = $('#harga_awal').val();
            var diskon_persen = $('#diskon_persen').val();
            var diskon_nominal = diskon_persen / 100 * harga_awal;
            var harga_akhir = harga_awal - diskon_nominal;
            $('#diskon_nominal').val(diskon_nominal);
            $('#harga_akhir').val(harga_akhir);
        })
        // cari nominal persen
        $('#diskon_nominal').on('keyup', function() {
            var harga_awal = $('#harga_awal').val();
            var diskon_nominal = $('#diskon_nominal').val();
            var diskon_persen = diskon_nominal / harga_awal * 100;
            var harga_akhir = harga_awal - diskon_nominal;
            $('#diskon_persen').val(diskon_persen);
            $('#harga_akhir').val(harga_akhir);
        })
        // load produk detail
        $('#produk_id').on('change', function() {
            var id = $('#produk_id').val();
            $.ajax({
                url: '{{ URL::to('admin/loadprodukasync') }}/' + id,
                type: 'get',
                dataType: 'json',
                success: function(data, status) {
                    if (status == 'success') {
                        $('#harga_awal').val(data.itemproduk.harga);
                    }
                },
                error: function(x, t, m) {}
            })
        })
    </script>
@endsection

resources/views/promo/edit.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col col-lg-6 col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Form Produk</h3>
                        <div class="card-tools">
                            <a href="{{ route('promo.index') }}" class="btn btn-sm btn-danger">
                                Tutup
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        @if (count($errors) > 0)
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-warning">{{ $error }}</div>
                            @endforeach
                        @endif
                        @if ($message = Session::get('error'))
                            <div class="alert alert-warning">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        <form action="{{ route('promo.update', $itempromo->id) }}" method="post">
                            {{ method_field('patch') }}
                            @csrf
                            <div class="row">
                                <div class="col">
                                    <div class="form-group">
                                        <label for="kode_produk">Kode Produk</label>
                                        <input type="text" name="kode_produk" id="kode_produk" class="form-control"
                                            disabled value={{ $itempromo->produk->kode_produk }}>
                                        <input type="hidden" name="produk_id" value={{ $itempromo->produk_id }}>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <label for="nama_produk">Nama Produk</label>
                                        <input type="text" name="nama_produk" id="nama_produk" class="form-control"
                                            disabled value={{ $itempromo->produk->nama_produk }}>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="harga_awal">Harga Awal</label>
                                <input type="text" name="harga_awal" id="harga_awal" class="form-control"
                                    value={{ $itempromo->harga_awal }}>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="form-group">
                                        <label for="diskon_persen">Diskon Persen</label>
                                        <input type="text" name="diskon_persen" id="diskon_persen" class="form-control"
                                            value={{ $itempromo->diskon_persen }}>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <label for="diskon_nominal">Diskon Nominal</label>
                                        <input type="text" name="diskon_nominal" id="diskon_nominal" class="form-control"
                                            value={{ $itempromo->diskon_nominal }}>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="harga_akhir">Harga Akhir</label>
                                <input type="text" name="harga_akhir" id="harga_akhir" class="form-control"
                                    value={{ $itempromo->harga_akhir }}>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Update</button>
                                <button type="reset" class="btn btn-warning">Reset</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        // cari nominal diskon
        $('#diskon_persen').on('keyup', function() {
            var harga_awal = $('#harga_awal').val();
            var diskon_persen = $('#diskon_persen').val();
            var diskon_nominal = diskon_persen / 100 * harga_awal;
            var harga_akhir = harga_awal - diskon_nominal;
            $('#diskon_nominal').val(diskon_nominal);
            $('#harga_akhir').val(harga_akhir);
        })
        // cari nominal persen
        $('#diskon_nominal').on('keyup', function() {
            var harga_awal = $('#harga_awal').val();
            var diskon_nominal = $('#diskon_nominal').val();
            var diskon_persen = diskon_nominal / harga_awal * 100;
            var harga_akhir = harga_awal - diskon_nominal;
            $('#diskon_persen').val(diskon_persen);
            $('#harga_akhir').val(harga_akhir);
        })
        // load produk detail
        $('#produk_id').on('change', function() {
            var id = $('#produk_id').val();
            $.ajax({
                url: '{{ URL::to('admin/loadprodukasync') }}/' + id,
                type: 'get',
                dataType: 'json',
                success: function(data, status) {
                    if (status == 'success') {
                        $('#harga_awal').val(data.itemproduk.harga);
                    }
                },
                error: function(x, t, m) {}
            })
        })
    </script>
@endsection

resources/views/promo/index.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="container-fluid">
        <!-- table produk -->
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Produk</h4>
                        <div class="card-tools">
                            <a href="{{ route('promo.create') }}" class="btn btn-sm btn-primary">
                                Baru
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="#">
                            <div class="row">
                                <div class="col">
                                    <input type="text" name="keyword" id="keyword" class="form-control"
                                        placeholder="ketik keyword disini">
                                </div>
                                <div class="col-auto">
                                    <button class="btn btn-primary">
                                        Cari
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="card-body">
                        @if ($message = Session::get('error'))
                            <div class="alert alert-warning">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th width="50px">No</th>
                                        <th>Gambar</th>
                                        <th>Kode</th>
                                        <th>Harga Awal</th>
                                        <th>Nama</th>
                                        <th>Diskon</th>
                                        <th>Harga Akhir</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($itempromo as $promo)
                                        <tr>
                                            <td>
                                                {{ ++$no }}
                                            </td>
                                            <td>
                                                @if ($promo->produk->foto != null)
                                                    <img src="{{ \Storage::url($promo->produk->foto) }}"
                                                        alt="{{ $promo->produk->nama_produk }}" width='150px'
                                                        class="img-thumbnail">
                                                @endif
                                            </td>
                                            <td>
                                                {{ $promo->produk->kode_produk }}
                                            </td>
                                            <td>
                                                {{ $promo->produk->nama_produk }}
                                            </td>
                                            <td>
                                                {{ number_format($promo->harga_awal, 2) }}
                                            </td>
                                            <td>
                                                {{ number_format($promo->diskon_nominal, 2) }}
                                                ({{ $promo->diskon_persen }}%)
                                            </td>
                                            <td>
                                                {{ number_format($promo->harga_akhir, 2) }}
                                            </td>
                                            <td>
                                                <a href="{{ route('promo.edit', $promo->id) }}"
                                                    class="btn btn-sm btn-primary mr-2 mb-2">
                                                    Edit
                                                </a>
                                                <form action="{{ route('promo.destroy', $promo->id) }}" method="post"
                                                    style="display:inline;">
                                                    @csrf
                                                    {{ method_field('delete') }}
                                                    <button type="submit" class="btn btn-sm btn-danger mb-2">
                                                        Hapus
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            {{ $itempromo->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection