routes/web.php
    <?php

    use App\Http\Controllers\AlamatPengirimanController;
    use App\Http\Controllers\CartController;
    use App\Http\Controllers\CartDetailController;
    use App\Http\Controllers\CustomerController;
    use App\Http\Controllers\DashboardController;
    use App\Http\Controllers\HomepageController;
    use App\Http\Controllers\ImageController;
    use App\Http\Controllers\KategoriController;
    use App\Http\Controllers\LaporanController;
    use App\Http\Controllers\LatihanController;
    use App\Http\Controllers\ProdukController;
    use App\Http\Controllers\ProdukPromoController;
    use App\Http\Controllers\SlideshowController;
    use App\Http\Controllers\TransaksiController;
    use App\Http\Controllers\UserController;
    use App\Http\Controllers\WishlistController;
    use Illuminate\Support\Facades\Auth;
    use Illuminate\Support\Facades\Route;

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    Route::get('/', [HomepageController::class, 'index']);
    Route::get('/about', [HomepageController::class, 'about']);
    Route::get('/kontak', [HomepageController::class, 'kontak']);
    Route::get('/kategori', [HomepageController::class, 'kategori']);
    Route::get('/kategori/{slug}', [HomepageController::class, 'kategoribyslug']);
    Route::get('/produk', [HomepageController::class, 'produk']);
    Route::get('produk/{id}', [HomepageController::class, 'produkdetail']);

    Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
        Route::get('/', [DashboardController::class, 'index']);
        // route kategori
        Route::resource('kategori', KategoriController::class);
        // route produk
        Route::resource('produk', ProdukController::class);
        // route customer
        Route::resource('customer', CustomerController::class);
        // route transaksi
        Route::resource('transaksi', TransaksiController::class);
        // profil
        Route::get('profil', [UserController::class, 'index']);
        // setting profil
        Route::get('setting', [UserController::class, 'setting']);
        // form laporan
        Route::get('laporan', [LaporanController::class, 'index']);
        // proses laporan
        Route::get('proseslaporan', [LaporanController::class, 'proses']);

        // image
        Route::get('image', [ImageController::class, 'index']);
        // simpan image
        Route::post('image', [ImageController::class, 'store']);
        // hapus image by id
        Route::delete('image/{id}', [ImageController::class, 'destroy']);


        // upload image kategori
        Route::post('imagekategori', [KategoriController::class, 'uploadimage']);
        // hapus image kategori
        Route::delete('imagekategori/{id}', [KategoriController::class, 'deleteimage']);

        // upload image produk
        Route::post('produkimage', [ProdukController::class, 'uploadimage']);
        // hapus image produk
        Route::delete('produkimage/{id}', [ProdukController::class, 'deleteimage']);

        // hapus image produk
        Route::delete('produkimage/{id}', [ProdukController::class, 'deleteimage']);
        // slideshow
        Route::resource('slideshow', SlideshowController::class);

        // produk promo
        Route::resource('promo', ProdukPromoController::class);
        // load async produk
        Route::get('loadprodukasync/{id}', [ProdukController::class, 'loadasync']);
        // wishlist
        Route::resource('wishlist', WishlistController::class);
    });
    // shopping cart
    Route::group(['middleware' => 'auth'], function () {
        // cart
        Route::resource('cart', CartController::class);
        Route::patch('kosongkan/{id}', [CartController::class, 'kosongkan']);
        // cart detail
        Route::resource('cartdetail', CartDetailController::class);

        // alamat pengiriman
        Route::resource('alamatpengiriman', AlamatPengirimanController::class);
        // checkout
        Route::get('checkout', [CartController::class, 'checkout']);
    });

    // Route::get('/', function () {
    //     return view('welcome');
    // });
    // Route::get('/halo', function () {
    //     return "Halo nama saya fadlur";
    // });
    // Route::get('/latihan', [LatihanController::class,'index']);
    // Route::get('/blog/{id}', [LatihanController::class,'blog']);
    // Route::get('/blog/{idblog}/komentar/{idkomentar}',[LatihanController::class,'komentar']);
    // Route::get('/beranda', [LatihanController::class,'beranda']);

    Auth::routes();
    Route::get('/home', function () {
        return redirect('/admin');
    });

app/Models/Kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    use HasFactory;

    protected $table = 'kategori';
    protected $fillable = [
        'kode_kategori',
        'nama_kategori',
        'slug_kategori',
        'deskripsi_kategori',
        'status',
        'foto',
        'user_id',
    ];

    public function user()
    { //user yang menginput data kategori
        return $this->belongsTo(User::class, 'user_id');
    }

    public function produk()
    {
        return $this->belongsTo(Produk::class, 'id', 'kategori_id');
    }
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kategori;
use Illuminate\Http\Request;

class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // kita ambil data kategori per halaman 20 data dan (paginate(20))
        // kita urutkan yang terakhir diiput yang paling atas (orderBy)
        $itemkategori = Kategori::orderBy('created_at', 'desc')->paginate(20);
        $data = ['title' => 'Kategori Produk', 'itemkategori' => $itemkategori];
        return view('kategori.index', $data)->with('no', ($request->input('page', 1) - 1) * 20);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $data = ['title' => 'Form Kategori'];
        return view('kategori.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'kode_kategori' => 'required|unique:kategori',
            'nama_kategori' => 'required',
            'slug_kategori' => 'required',
            'deskripsi_kategori' => 'required',
        ]);
        $itemuser = $request->user(); //kita panggil data user yang sedang login
        $inputan = $request->all(); //kita masukkan semua variabel data yang diinput ke variabel $inputan
        $inputan['user_id'] = $itemuser->id;
        $inputan['slug_kategori'] = \Str::slug($request->slug_kategori); //kita buat slug biar pemisahnya menjadi strip (-)
        //slug kita gunakan nanti pas buka produk per kategori
        $inputan['status'] = 'publish'; //status kita set langsung publish saja
        $itemkategori = Kategori::create($inputan);
        return redirect()
            ->route('kategori.index')
            ->with('success', 'Data kategori berhasil disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $itemkategori = Kategori::findOrFail($id); //cari berdasarkan id = $id,
        // kalo ga ada error page not found 404
        $data = [
            'title' => 'Form Edit Kategori',
            'itemkategori' => $itemkategori,
        ];
        return view('kategori.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama_kategori' => 'required',
            'slug_kategori' => 'required',
            'deskripsi_kategori' => 'required',
        ]);
        $itemkategori = Kategori::findOrFail($id); //cari berdasarkan id = $id,
        // kalo ga ada error page not found 404
        $slug = \Str::slug($request->slug_kategori); //slug kita gunakan nanti pas buka produk per kategori
        // kita validasi dulu, biar tidak ada slug yang sama
        $validasislug = Kategori::where('id', '!=', $id) //yang id-nya tidak sama dengan $id
            ->where('slug_kategori', $slug)
            ->first();
        if ($validasislug) {
            return back()->with('error', 'Slug sudah ada, coba yang lain');
        } else {
            $inputan = $request->all();
            $inputan['slug'] = $slug;
            $itemkategori->update($inputan);
            return redirect()
                ->route('kategori.index')
                ->with('success', 'Data berhasil diupdate');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $itemkategori = Kategori::findOrFail($id); //cari berdasarkan id = $id,
        // kalo ga ada error page not found 404
        if ($itemkategori->produk()->count() > 0) {
            // dicek dulu, kalo ada produk di dalam kategori maka proses hapus dihentikan
            return back()->with('error', 'Hapus dulu produk di dalam kategori ini, proses dihentikan');
        } else {
            if ($itemkategori->delete()) {
                return back()->with('success', 'Data berhasil dihapus');
            } else {
                return back()->with('error', 'Data gagal dihapus');
            }
        }
    }
    public function uploadimage(Request $request)
    {
        $this->validate($request, [
            'image' => 'required|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'kategori_id' => 'required',
        ]);
        $itemuser = $request->user();
        $itemkategori = Kategori::where('user_id', $itemuser->id)
            ->where('id', $request->kategori_id)
            ->first();
        if ($itemkategori) {
            $fileupload = $request->file('image');
            $folder = $request->file('image')->store('public/images');
            $itemgambar = (new ImageController())->upload($fileupload, $itemuser, $folder);
            $inputan['foto'] = $itemgambar->url; //ambil url file yang barusan diupload
            $itemkategori->update($inputan);
            return back()->with('success', 'Image berhasil diupload');
        } else {
            return back()->with('error', 'Kategori tidak ditemukan');
        }
    }

    public function deleteimage(Request $request, $id)
    {
        $itemuser = $request->user();
        $itemkategori = Kategori::where('user_id', $itemuser->id)
            ->where('id', $id)
            ->first();
        if ($itemkategori) {
            // kita cari dulu database berdasarkan url gambar
            $itemgambar = \App\Image::where('url', $itemkategori->foto)->first();
            // hapus imagenya
            if ($itemgambar) {
                \Storage::delete($itemgambar->url);
                $itemgambar->delete();
            }
            // baru update foto kategori
            $itemkategori->update(['foto' => null]);
            return back()->with('success', 'Data berhasil dihapus');
        } else {
            return back()->with('error', 'Data tidak ditemukan');
        }
    }
}

resources/views/kategori/create.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col col-lg-6 col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Form Kategori</h3>
                        <div class="card-tools">
                            <a href="{{ route('kategori.index') }}" class="btn btn-sm btn-danger">
                                Tutup
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        @if (count($errors) > 0)
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-warning">{{ $error }}</div>
                            @endforeach
                        @endif
                        @if ($message = Session::get('error'))
                            <div class="alert alert-warning">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        <form action="{{ route('kategori.store') }}" method='POST'>
                            @csrf
                            <div class="form-group">
                                <label for="kode_kategori">Kode Kategori</label>
                                <input type="text" name="kode_kategori" id="kode_kategori" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="nama_kategori">Nama Kategori</label>
                                <input type="text" name="nama_kategori" id="nama_kategori" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="slug_kategori">Slug Kategori</label>
                                <input type="text" name="slug_kategori" id="slug_kategori" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="deskripsi_kategori">Deskripsi</label>
                                <textarea name="deskripsi_kategori" id="deskripsi_kategori" cols="30" rows="5" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                                <button type="reset" class="btn btn-warning">Reset</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/kategori/edit.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col col-lg-6 col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Form Edit Kategori</h3>
                        <div class="card-tools">
                            <a href="{{ route('kategori.index') }}" class="btn btn-sm btn-danger">
                                Tutup
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        @if (count($errors) > 0)
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-warning">{{ $error }}</div>
                            @endforeach
                        @endif
                        @if ($message = Session::get('error'))
                            <div class="alert alert-warning">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        <form action="{{ route('kategori.update', $itemkategori->id) }}" method="post">
                            @csrf
                            {{ method_field('patch') }}
                            <div class="form-group">
                                <label for="kode_kategori">Kode Kategori</label>
                                <input type="text" name="kode_kategori" id="kode_kategori" class="form-control"
                                    value={{ $itemkategori->kode_kategori }}>
                            </div>
                            <div class="form-group">
                                <label for="nama_kategori">Nama Kategori</label>
                                <input type="text" name="nama_kategori" id="nama_kategori" class="form-control"
                                    value={{ $itemkategori->nama_kategori }}>
                            </div>
                            <div class="form-group">
                                <label for="slug_kategori">Slug Kategori</label>
                                <input type="text" name="slug_kategori" id="slug_kategori" class="form-control"
                                    value={{ $itemkategori->slug_kategori }}>
                            </div>
                            <div class="form-group">
                                <label for="deskripsi_kategori">Deskripsi</label>
                                <textarea name="deskripsi_kategori" id="deskripsi_kategori" cols="30" rows="5"
                                    class="form-control">{{ $itemkategori->deskripsi_kategori }}</textarea>
                            </div>
                            <div class="form-group">
                                <label for="status">Status</label>
                                <select name="status" id="status" class="form-control">
                                    <option value="publish" {{ $itemkategori->status == 'publish' ? 'selected' : '' }}>
                                        Publish</option>
                                    <option value="unpublish" {{ $itemkategori->status == 'unpublish' ? 'selected' : '' }}>
                                        Unpublish</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Update</button>
                                <button type="reset" class="btn btn-warning">Reset</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/kategori/index.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="container-fluid">
        <!-- table kategori -->
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Kategori Produk</h4>
                        <div class="card-tools">
                            <a href="{{ route('kategori.create') }}" class="btn btn-sm btn-primary">
                                Baru
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="#">
                            <div class="row">
                                <div class="col">
                                    <input type="text" name="keyword" id="keyword" class="form-control"
                                        placeholder="ketik keyword disini">
                                </div>
                                <div class="col-auto">
                                    <button class="btn btn-primary">
                                        Cari
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="card-body">
                        @if ($message = Session::get('error'))
                            <div class="alert alert-warning">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        @if (count($errors) > 0)
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-warning">{{ $error }}</div>
                            @endforeach
                        @endif
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th width="50px">No</th>
                                        <th>Gambar</th>
                                        <th>Kode</th>
                                        <th>Nama</th>
                                        <th>Jumlah Produk</th>
                                        <th>Status</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($itemkategori as $kategori)
                                        <tr>
                                            <td>
                                                {{ ++$no }}
                                            </td>
                                            <td>
                                                <!-- image kategori -->
                                                @if ($kategori->foto != null)
                                                    <img src="{{ \Storage::url($kategori->foto) }}"
                                                        alt="{{ $kategori->nama_kategori }}" width='150px'
                                                        class="img-thumbnail mb-2">
                                                    <br>
                                                    <form action="{{ url('/admin/imagekategori/' . $kategori->id) }}"
                                                        method="post" style="display:inline;">
                                                        @csrf
                                                        {{ method_field('delete') }}
                                                        <button type="submit" class="btn btn-sm btn-danger mb-2">
                                                            Hapus
                                                        </button>
                                                    </form>
                                                @else
                                                    <form action="{{ url('/admin/imagekategori') }}" method="post"
                                                        enctype="multipart/form-data" class="form-inline">
                                                        @csrf
                                                        <div class="form-group">
                                                            <input type="file" name="image" id="image">
                                                            <input type="hidden" name="kategori_id"
                                                                value={{ $kategori->id }}>
                                                        </div>
                                                        <div class="form-group">
                                                            <button class="btn btn-primary">Upload</button>
                                                        </div>
                                                    </form>
                                                @endif
                                                <!-- end image kategori -->
                                            </td>
                                            <td>
                                                {{ $kategori->kode_kategori }}
                                            </td>
                                            <td>
                                                {{ $kategori->nama_kategori }}
                                            </td>
                                            <td>
                                                {{ $kategori->produk ? $kategori->produk()->count() : '0' }} Produk
                                            </td>
                                            <td>
                                                {{ $kategori->status }}
                                            </td>
                                            <td>
                                                <a href="{{ route('kategori.edit', $kategori->id) }}"
                                                    class="btn btn-sm btn-primary mr-2 mb-2">
                                                    Edit
                                                </a>
                                                <form action="{{ route('kategori.destroy', $kategori->id) }}"
                                                    method="post" style="display:inline;">
                                                    @csrf
                                                    {{ method_field('delete') }}
                                                    <button type="submit" class="btn btn-sm btn-danger mb-2">
                                                        Hapus
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            <!-- untuk menampilkan link page, tambahkan skrip di bawah ini -->
                            {{ $itemkategori->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection